import type { ParsedEmployee } from '../types/absenteeism';

export const sampleAbsenteeismData: ParsedEmployee[] = [
  {
    info: {
      name: 'Maria Silva Santos',
      registration: '1001',
      position: 'Analista Financeiro',
      team: 'Financeiro',
      sector: 'Administrativo',
      unit: 'Matriz',
    },
    periodStart: new Date('2026-01-01'),
    periodEnd: new Date('2026-01-31'),
    records: [
      {
        date: new Date('2026-01-06'),
        dayOfWeek: 'seg',
        expectedHours: 8,
        workedHours: 0,
        absentHours: 8,
        normalHours: 0,
        overtimeHours: 0,
        reason: 'Atestado medico',
        absenceType: 'saude',
        isComputable: true,
      },
      {
        date: new Date('2026-01-07'),
        dayOfWeek: 'ter',
        expectedHours: 8,
        workedHours: 0,
        absentHours: 8,
        normalHours: 0,
        overtimeHours: 0,
        reason: 'Atestado medico',
        absenceType: 'saude',
        isComputable: true,
      },
      {
        date: new Date('2026-01-15'),
        dayOfWeek: 'qua',
        expectedHours: 8,
        workedHours: 6,
        absentHours: 2,
        normalHours: 6,
        overtimeHours: 0,
        reason: 'Atraso',
        absenceType: 'atraso',
        isComputable: true,
      },
    ],
  },
  {
    info: {
      name: 'Joao Carlos Oliveira',
      registration: '1002',
      position: 'Operador',
      team: 'Producao',
      sector: 'Operacional',
      unit: 'Matriz',
    },
    periodStart: new Date('2026-01-01'),
    periodEnd: new Date('2026-01-31'),
    records: [
      {
        date: new Date('2026-01-08'),
        dayOfWeek: 'qua',
        expectedHours: 8,
        workedHours: 0,
        absentHours: 8,
        normalHours: 0,
        overtimeHours: 0,
        reason: 'Falta sem justificativa',
        absenceType: 'injustificada',
        isComputable: true,
      },
      {
        date: new Date('2026-01-20'),
        dayOfWeek: 'seg',
        expectedHours: 8,
        workedHours: 0,
        absentHours: 8,
        normalHours: 0,
        overtimeHours: 0,
        reason: 'Falta sem justificativa',
        absenceType: 'injustificada',
        isComputable: true,
      },
      {
        date: new Date('2026-01-21'),
        dayOfWeek: 'ter',
        expectedHours: 8,
        workedHours: 0,
        absentHours: 8,
        normalHours: 0,
        overtimeHours: 0,
        reason: 'Falta sem justificativa',
        absenceType: 'injustificada',
        isComputable: true,
      },
    ],
  },
  {
    info: {
      name: 'Ana Paula Costa',
      registration: '1003',
      position: 'Assistente Administrativo',
      team: 'RH',
      sector: 'Administrativo',
      unit: 'Matriz',
    },
    periodStart: new Date('2026-01-01'),
    periodEnd: new Date('2026-01-31'),
    records: [
      {
        date: new Date('2026-01-10'),
        dayOfWeek: 'sex',
        expectedHours: 8,
        workedHours: 0,
        absentHours: 8,
        normalHours: 0,
        overtimeHours: 0,
        reason: 'Ferias',
        absenceType: 'ferias',
        isComputable: false,
      },
      {
        date: new Date('2026-01-13'),
        dayOfWeek: 'seg',
        expectedHours: 8,
        workedHours: 0,
        absentHours: 8,
        normalHours: 0,
        overtimeHours: 0,
        reason: 'Ferias',
        absenceType: 'ferias',
        isComputable: false,
      },
      {
        date: new Date('2026-01-22'),
        dayOfWeek: 'qua',
        expectedHours: 8,
        workedHours: 5,
        absentHours: 3,
        normalHours: 5,
        overtimeHours: 0,
        reason: 'Consulta medica',
        absenceType: 'saude',
        isComputable: true,
      },
    ],
  },
  {
    info: {
      name: 'Pedro Henrique Lima',
      registration: '1004',
      position: 'Tecnico',
      team: 'Producao',
      sector: 'Operacional',
      unit: 'Filial 01',
    },
    periodStart: new Date('2026-01-01'),
    periodEnd: new Date('2026-01-31'),
    records: [
      {
        date: new Date('2026-01-02'),
        dayOfWeek: 'qui',
        expectedHours: 8,
        workedHours: 6.5,
        absentHours: 1.5,
        normalHours: 6.5,
        overtimeHours: 0,
        reason: 'Atraso',
        absenceType: 'atraso',
        isComputable: true,
      },
      {
        date: new Date('2026-01-16'),
        dayOfWeek: 'qui',
        expectedHours: 8,
        workedHours: 7,
        absentHours: 1,
        normalHours: 7,
        overtimeHours: 0,
        reason: 'Atraso',
        absenceType: 'atraso',
        isComputable: true,
      },
    ],
  },
  {
    info: {
      name: 'Fernanda Rodrigues',
      registration: '1005',
      position: 'Supervisora',
      team: 'Financeiro',
      sector: 'Administrativo',
      unit: 'Matriz',
    },
    periodStart: new Date('2026-01-01'),
    periodEnd: new Date('2026-01-31'),
    records: [
      {
        date: new Date('2026-01-25'),
        dayOfWeek: 'sab',
        expectedHours: 0,
        workedHours: 0,
        absentHours: 0,
        normalHours: 0,
        overtimeHours: 0,
        reason: 'Folga',
        absenceType: 'folga',
        isComputable: false,
      },
    ],
  },
];

export const sampleParsedResult = {
  success: true,
  employees: sampleAbsenteeismData,
  errors: [],
  warnings: ['Alguns colaboradores nao possuem CPF no documento'],
  unparsedLines: [
    {
      page: 1,
      lineNumber: 45,
      text: '-- dados incompletos --',
      reason: 'Formato de data nao reconhecido',
    },
  ],
};
